spring:
  datasource:
    url : jdbc:mysql://localhost:3306/cap?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:h2:mem:library;MODE=MYSQL;NON_KEYWORDS=USER
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console