name: Deploy Spring Boot App with Gradle and Docker

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test  # 테스트 제외하고 빌드

      - name: Find JAR File
        id: get_jar
        run: echo "JAR_FILE=$(ls build/libs/*.jar | grep -v 'plain' | head -n 1)" >> $GITHUB_ENV

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "${{ env.JAR_FILE }}"
          target: "~/app"

      - name: Restart Application on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Reloading Systemd and Restarting Spring Boot Application..."
            sudo systemctl daemon-reload
            sudo systemctl restart spring-boot-app
            sudo systemctl status spring-boot-app --no-pager